# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Culturally Responsive Computing in Middle School
# Description of the Site
description: A project to expand the accessibility of computer science to middle schoolers in Montana, using storytelling.
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://montanastorytelling.github.io/beaded-bag-trainings/assets/images/beehive.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: storytelling@montana.edu
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username:
github_username: https://github.com/montanastorytelling/
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Training Team
# URL for the Image of the Author
author-image: https://www.montana.edu/creativeservices/images/MSU-mm-sm.jpg
author-image1: https://montanastorytelling.github.io/beaded-bag-trainings/assets/images/barbara.jpg
author-image2: https://montanastorytelling.github.io/beaded-bag-trainings/assets/images/sweeney.jpg
author-image3: https://montanastorytelling.github.io/beaded-bag-trainings/assets/images/brittany.jpg
author-image4: https://montanastorytelling.github.io/beaded-bag-trainings/assets/images/stacey.jpg
# 60 Words About the Author
author-about: The storytelling project spans five departments at Montana State University, and involves undergraduate and graduate students, faculty, postdoctoral researchers, staff, and K-12 teachers throughout Montana. Our objective is to expose middle school students to basic computer science, and increase the accessibility of computer science throughout Montana.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.montana.edu/storytelling/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
